[package]
name = "libics-dm-azure-sys"
version = "0.1.0"
edition = "2018"
authors = ["Joerg Zeidler <joerg.zeidler@conplement.de>"]
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
bindgen="0.55.1"
cmake = "0.1.44"
pkg-config = "0.3.18"
