[package]
name = "ics-dm-azure-sys"
version = "0.1.1"
edition = "2018"
authors = ["Joerg Zeidler <joerg.zeidler@conplement.de>"]
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
bindgen = "0.55.1"
glob = "0.3.0"
